# Generated by Django 6.0.2 on 2026-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name (EN)'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='dry_cleaning_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dry Cleaning Price'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='ironing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ironing Price'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Name (EN)'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='washing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Washing Price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name (AR)'),
        ),
        migrations.AlterField(
            model_name='laundryitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item Name (AR)'),
        ),
    ]
