# Generated by Django 6.0.2 on 2026-02-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_laundryitem_price_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items_images/'),
        ),
    ]
