# Generated by Django 6.0.2 on 2026-02-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_laundryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Item Image'),
        ),
    ]
