# Generated by Django 6.0.2 on 2026-03-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_laundryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryitem',
            name='dry_cleaning_express_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dry Cleaning Express Price'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='ironing_express_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ironing Express Price'),
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='washing_express_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Washing Express Price'),
        ),
    ]
