# Generated by Django 6.0.2 on 2026-03-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_laundryitem_dry_cleaning_express_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
