# Generated by Django 6.0.2 on 2026-02-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(default='General', max_length=100, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
