# Generated by Django 6.0.2 on 2026-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customerprofile_user_customerprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Aldobi', 'Aldobi'), ('Cleano', 'Cleano'), ('monthly', 'monthly')], default='Uncategorized', max_length=50, verbose_name='Customer Category'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='file_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='File Number'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='fold_type',
            field=models.CharField(choices=[('Folded', 'Folded'), ('Hanged', 'Hanged')], default='Folded', max_length=20, verbose_name='Fold Type'),
        ),
    ]
