# Generated by Django 6.0.2 on 2026-02-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Category',
                'verbose_name_plural': 'Customer Categories',
            },
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_category',
            field=models.CharField(default='Uncategorized', max_length=50, verbose_name='Customer Category'),
        ),
    ]
