# Generated by Django 6.0.2 on 2026-03-02 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customercategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_pos', models.BooleanField(default=False)),
                ('can_access_customers', models.BooleanField(default=False)),
                ('can_access_orders', models.BooleanField(default=False)),
                ('can_sell_gift_cards', models.BooleanField(default=False)),
                ('can_recharge_wallet', models.BooleanField(default=False)),
                ('can_add_expenses', models.BooleanField(default=False)),
                ('can_apply_discount', models.BooleanField(default=False)),
                ('can_delete_from_cart', models.BooleanField(default=False)),
                ('can_add_new_customer', models.BooleanField(default=False)),
                ('can_pay_with_wallet_gc', models.BooleanField(default=False)),
                ('can_edit_customer', models.BooleanField(default=False)),
                ('can_delete_customer', models.BooleanField(default=False)),
                ('can_pay_debt', models.BooleanField(default=False)),
                ('can_add_category', models.BooleanField(default=False)),
                ('can_view_history', models.BooleanField(default=False)),
                ('can_void_order', models.BooleanField(default=False)),
                ('can_access_finance_center', models.BooleanField(default=False)),
                ('can_change_order_status', models.BooleanField(default=False)),
                ('can_add_items_to_order', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
