# Generated by Django 6.0.2 on 2026-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset / أصول'), ('LIABILITY', 'Liability / خصوم'), ('REVENUE', 'Revenue / إيرادات'), ('EXPENSE', 'Expense / مصروفات')], default='ASSET', max_length=20)),
                ('group_name', models.CharField(max_length=100, verbose_name='المجموعة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
