# Generated by Django 6.0.2 on 2026-03-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_financialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customercategory', verbose_name='Customer Category'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='fold_type',
            field=models.CharField(choices=[('Folded', 'Folded / مطوي'), ('Hanged', 'Hanged / معلق')], default='Folded', max_length=20, verbose_name='Fold Type'),
        ),
    ]
