# Generated by Django 6.0.2 on 2026-03-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customerprofile_customer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='fold_type',
            field=models.CharField(choices=[('Folded', 'Folded'), ('Hanged', 'Hanged')], default='Folded', max_length=20, verbose_name='Fold Type'),
        ),
    ]
