# Generated by Django 6.0.2 on 2026-03-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customerprofile_fold_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_category',
            field=models.CharField(default='Uncategorized', max_length=50, verbose_name='Customer Category'),
        ),
    ]
