# Generated by Django 6.0.2 on 2026-03-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customerprofile_customer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ القيد')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع (مثال: رقم الفاتورة)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان / الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مدين (Debit)')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='دائن (Credit)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.financialaccount', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.journalentry')),
            ],
        ),
    ]
