# Generated by Django 6.0.2 on 2026-02-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Card Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='Void Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('WALLET', 'Wallet')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price per item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='services.laundryitem', verbose_name='Laundry Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
        ),
    ]
