# Generated by Django 6.0.2 on 2026-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_giftcard_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Order Remarks'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_express',
            field=models.BooleanField(default=False, verbose_name='Express Service'),
        ),
    ]
