# Generated by Django 6.0.2 on 2026-02-20 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_address_and_more'),
        ('orders', '0003_order_discount_percentage_order_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='code',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='is_used',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerprofile', verbose_name='Purchaser'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Initial Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('WALLET', 'Wallet'), ('GIFT_CARD', 'Gift Card')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
