# Generated by Django 6.0.2 on 2026-02-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_giftcard_amount_remove_giftcard_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default='PICKUP', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_type',
            field=models.CharField(choices=[('HANGER', 'Hanger'), ('FOLDED', 'Folded')], default='FOLDED', max_length=10),
        ),
    ]
