# Generated by Django 6.0.2 on 2026-02-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_logistics_type_order_processing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
