# Generated by Django 6.0.2 on 2026-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
