# Generated by Django 6.0.2 on 2026-02-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20, verbose_name='Item Status'),
        ),
    ]
