# Generated by Django 6.0.2 on 2026-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing Start Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ready for Collection Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At / Registered At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
