# Generated by Django 6.0.2 on 2026-02-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processing_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Washing/Ironing Start'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ready at Time'),
        ),
    ]
