# Generated by Django 6.0.2 on 2026-03-05 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_expensecategory_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الجلسة')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإغلاق')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wallet_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenses_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deleted_orders_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكاش المتوقع')),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكاش الفعلي')),
                ('actual_card', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='شبكة الفعلي')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='العجز/الزيادة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
            ],
            options={
                'verbose_name': 'تقرير وردية',
                'verbose_name_plural': 'تقارير الورديات',
                'ordering': ['-closed_at'],
            },
        ),
    ]
