# Generated by Django 6.0.2 on 2026-03-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_payment_created_at_shiftreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode/SKU')),
                ('name_en', models.CharField(max_length=200, verbose_name='Product Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic Name')),
                ('product_type', models.CharField(default='Consumable', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('opening_stock', models.IntegerField(default=0)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('allow_zero_stock', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
