# Generated by Django 6.0.2 on 2026-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_inventoryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered'), ('VOID', 'Void / Cancelled')], default='PENDING', max_length=20),
        ),
    ]
